name: AutoMinecraft
version: '${project.version}'
main: jordandesotle.autominecraft.AutoMinecraft
api-version: 1.20
authors: [ JordanDeSotle ]
description: Capstone project for CS420 and CS421

commands:
  startBot:
    description: Start running the bot
    usage: /startBot